# Generated by Django 5.0.1 on 2024-02-24 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_areatrabajo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=255)),
                ('contraseña', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('n_ingreso', models.CharField(max_length=255)),
                ('equipo', models.CharField(max_length=255)),
                ('n_serie', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('fecha_ingreso', models.CharField(max_length=255)),
                ('fecha_finalizacion', models.CharField(max_length=255)),
                ('falla', models.CharField(max_length=255)),
                ('Obeservacion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=False)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tu_app.cliente')),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tu_app.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('falla', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_finalizacion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=False)),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tu_app.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='AreaDetalle',
            fields=[
                ('id_areadetalle', models.AutoField(primary_key=True, serialize=False)),
                ('id_areatrabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tu_app.area')),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tu_app.trabajador')),
            ],
        ),
    ]
